import { readOriginInfo, readSiteConfigs } from "@wraithwalker/mcp-server/fixture-reader";
import { EDITOR_CONTEXT_FILES, DEFAULT_CONTEXT_FILES } from "./constants.mjs";

interface ApiEndpoint {
  method: string;
  pathname: string;
  status: number;
  mimeType: string;
  fixtureDir: string;
}

interface StaticResourceManifest {
  resourcesByPathname: Record<string, Array<{ resourceType: string }>>;
}

interface OriginInfo {
  origin: string;
  originKey: string;
  manifest: StaticResourceManifest | null;
  apiEndpoints: ApiEndpoint[];
}
import type { FsGateway } from "./fs-gateway.mjs";
import {
  inferTypeNode,
  mergeTypeNodes,
  pathToInterfaceName,
  renderBarrelFile,
  renderDtsFile,
  type TypeNode
} from "./type-extractor.mjs";

interface ApiEndpointSummary {
  method: string;
  pathname: string;
  status: number;
  mimeType: string;
  responseShape: string | null;
  typeNode: TypeNode | null;
}

interface OriginSummary {
  origin: string;
  originKey: string;
  apiEndpoints: ApiEndpointSummary[];
  staticAssets: Record<string, number>;
  totalStaticAssets: number;
}

function inferJsonShape(value: unknown, indent = 0): string {
  if (value === null) return "null";
  if (typeof value === "string") return "string";
  if (typeof value === "number") return "number";
  if (typeof value === "boolean") return "boolean";

  if (Array.isArray(value)) {
    if (value.length === 0) return "unknown[]";
    return `${inferJsonShape(value[0], indent)}[]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{}";
    const pad = "  ".repeat(indent + 1);
    const closePad = "  ".repeat(indent);
    const lines = entries.map(([key, val]) => `${pad}${key}: ${inferJsonShape(val, indent + 1)}`);
    return `{\n${lines.join(";\n")};\n${closePad}}`;
  }

  return "unknown";
}

function buildOriginSummary(info: OriginInfo, endpointDetails: ApiEndpointSummary[]): OriginSummary {
  const staticAssets: Record<string, number> = {};
  let totalStaticAssets = 0;

  if (info.manifest) {
    for (const entries of Object.values(info.manifest.resourcesByPathname)) {
      for (const entry of entries) {
        const type = entry.resourceType || "Other";
        staticAssets[type] = (staticAssets[type] || 0) + 1;
        totalStaticAssets++;
      }
    }
  }

  return {
    origin: info.origin,
    originKey: info.originKey,
    apiEndpoints: endpointDetails,
    staticAssets,
    totalStaticAssets
  };
}

async function enrichEndpoints(rootPath: string, gateway: FsGateway, info: OriginInfo): Promise<ApiEndpointSummary[]> {
  const results: ApiEndpointSummary[] = [];

  for (const ep of info.apiEndpoints) {
    let responseShape: string | null = null;
    let typeNode: TypeNode | null = null;

    if (ep.mimeType.includes("json")) {
      try {
        const bodyPath = `${ep.fixtureDir}/response.body`;
        const bodyText = await gateway.readText(rootPath, bodyPath);
        const parsed = JSON.parse(bodyText);
        responseShape = inferJsonShape(parsed);
        typeNode = inferTypeNode(parsed);
      } catch {
        // Body not readable or not JSON
      }
    }

    results.push({
      method: ep.method,
      pathname: ep.pathname,
      status: ep.status,
      mimeType: ep.mimeType,
      responseShape,
      typeNode
    });
  }

  return results;
}

function renderContextMarkdown(origins: OriginSummary[], generatedAt: string): string {
  const lines: string[] = [];

  lines.push("# WraithWalker Fixture Context");
  lines.push("");
  lines.push(`Generated: ${generatedAt}`);
  lines.push("");
  lines.push("This file describes the captured network fixtures in this directory.");
  lines.push("It is auto-generated by the WraithWalker CLI or extension.");
  lines.push("");

  for (const origin of origins) {
    lines.push(`## ${origin.origin}`);
    lines.push("");

    if (origin.apiEndpoints.length > 0) {
      lines.push("### API Endpoints");
      lines.push("");
      lines.push("| Method | Path | Status | Content Type |");
      lines.push("|--------|------|--------|--------------|");
      for (const ep of origin.apiEndpoints) {
        lines.push(`| ${ep.method} | ${ep.pathname} | ${ep.status} | ${ep.mimeType} |`);
      }
      lines.push("");

      const jsonEndpoints = origin.apiEndpoints.filter((ep) => ep.responseShape);
      if (jsonEndpoints.length > 0) {
        lines.push("### Response Shapes");
        lines.push("");
        for (const ep of jsonEndpoints) {
          lines.push(`#### ${ep.method} ${ep.pathname} (${ep.status})`);
          lines.push("");
          lines.push("```typescript");
          lines.push(ep.responseShape!);
          lines.push("```");
          lines.push("");
        }
      }
    }

    if (origin.totalStaticAssets > 0) {
      lines.push("### Static Assets");
      lines.push("");
      const parts = Object.entries(origin.staticAssets)
        .sort(([, a], [, b]) => b - a)
        .map(([type, count]) => `${type}: ${count}`);
      lines.push(parts.join(" | "));
      lines.push("");
    }

    if (origin.apiEndpoints.length === 0 && origin.totalStaticAssets === 0) {
      lines.push("No captured fixtures found for this origin.");
      lines.push("");
    }
  }

  if (origins.some((o) => o.apiEndpoints.length > 0)) {
    lines.push("## Suggested Agent Tasks");
    lines.push("");
    const firstApi = origins.find((o) => o.apiEndpoints.length > 0);
    if (firstApi) {
      const ep = firstApi.apiEndpoints[0];
      lines.push(`- Modify the \`${ep.method} ${ep.pathname}\` fixture to return an error status and test error handling`);
      lines.push(`- Change response data in \`${ep.method} ${ep.pathname}\` to test edge cases (empty arrays, null fields, large payloads)`);
    }
    lines.push("- Add new fixture files for endpoints that don't exist yet to support offline development");
    lines.push("- Generate TypeScript interfaces from the response shapes above");
    lines.push("");
  }

  return lines.join("\n");
}

export async function generateContext(
  rootPath: string,
  gateway: FsGateway,
  editorId?: string
): Promise<string> {
  const configs = await readSiteConfigs(rootPath);
  const origins: OriginSummary[] = [];

  for (const config of configs) {
    const info = await readOriginInfo(rootPath, config);
    const endpoints = await enrichEndpoints(rootPath, gateway, info);
    origins.push(buildOriginSummary(info, endpoints));
  }

  const generatedAt = new Date().toISOString();
  const markdown = renderContextMarkdown(origins, generatedAt);

  // Write context files
  const fileNames = EDITOR_CONTEXT_FILES[editorId || ""] || DEFAULT_CONTEXT_FILES;
  for (const fileName of fileNames) {
    await gateway.writeText(rootPath, fileName, markdown);
  }

  // Generate .d.ts types
  const moduleNames: string[] = [];
  for (const origin of origins) {
    const typedEndpoints = origin.apiEndpoints.filter((ep) => ep.typeNode !== null);
    if (typedEndpoints.length === 0) continue;

    const byKey = new Map<string, { name: string; node: TypeNode }>();
    for (const ep of typedEndpoints) {
      const interfaceName = pathToInterfaceName(ep.method, ep.pathname);
      const existing = byKey.get(interfaceName);
      if (existing && ep.typeNode) {
        existing.node = mergeTypeNodes(existing.node, ep.typeNode);
      } else if (ep.typeNode) {
        byKey.set(interfaceName, { name: interfaceName, node: ep.typeNode });
      }
    }

    const declarations = [...byKey.values()];
    const dtsContent = renderDtsFile(declarations);
    await gateway.writeText(rootPath, `.wraithwalker/types/${origin.originKey}.d.ts`, dtsContent);
    moduleNames.push(origin.originKey);
  }

  if (moduleNames.length > 0) {
    await gateway.writeText(rootPath, ".wraithwalker/types/index.d.ts", renderBarrelFile(moduleNames));
  }

  return markdown;
}
