import {
  DEFAULT_CONTEXT_FILES,
  EDITOR_CONTEXT_FILES
} from "./constants.mjs";
import { readOriginInfo, readSiteConfigs, type OriginInfo } from "./fixtures.mjs";
import {
  inferTypeNode,
  mergeTypeNodes,
  pathToInterfaceName,
  renderBarrelFile,
  renderDtsFile,
  type TypeNode
} from "./type-extractor.mjs";

export interface FsGateway {
  exists(rootPath: string, relativePath: string): Promise<boolean>;
  readJson<T>(rootPath: string, relativePath: string): Promise<T>;
  readOptionalJson<T>(rootPath: string, relativePath: string): Promise<T | null>;
  readText(rootPath: string, relativePath: string): Promise<string>;
  writeText(rootPath: string, relativePath: string, content: string): Promise<void>;
  writeJson(rootPath: string, relativePath: string, value: unknown): Promise<void>;
  listDirectory(rootPath: string, relativePath: string): Promise<Array<{ name: string; kind: "file" | "directory" }>>;
}

interface ApiEndpointSummary {
  method: string;
  pathname: string;
  status: number;
  mimeType: string;
  responseShape: string | null;
  typeNode: TypeNode | null;
}

interface OriginSummary {
  origin: string;
  originKey: string;
  apiEndpoints: ApiEndpointSummary[];
  staticAssets: Record<string, number>;
  totalStaticAssets: number;
}

function inferJsonShape(value: unknown, indent = 0): string {
  if (value === null) return "null";
  if (typeof value === "string") return "string";
  if (typeof value === "number") return "number";
  if (typeof value === "boolean") return "boolean";

  if (Array.isArray(value)) {
    if (value.length === 0) return "unknown[]";
    return `${inferJsonShape(value[0], indent)}[]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value);
    if (entries.length === 0) return "{}";
    const pad = "  ".repeat(indent + 1);
    const closePad = "  ".repeat(indent);
    const lines = entries.map(([key, val]) => `${pad}${key}: ${inferJsonShape(val, indent + 1)}`);
    return `{\n${lines.join(";\n")};\n${closePad}}`;
  }

  return "unknown";
}

function buildOriginSummary(info: OriginInfo, endpointDetails: ApiEndpointSummary[]): OriginSummary {
  const staticAssets: Record<string, number> = {};
  let totalStaticAssets = 0;

  if (info.manifest) {
    for (const entries of Object.values(info.manifest.resourcesByPathname)) {
      for (const entry of entries) {
        const type = entry.resourceType || "Other";
        staticAssets[type] = (staticAssets[type] || 0) + 1;
        totalStaticAssets++;
      }
    }
  }

  return {
    origin: info.origin,
    originKey: info.originKey,
    apiEndpoints: endpointDetails,
    staticAssets,
    totalStaticAssets
  };
}

async function enrichEndpoints(rootPath: string, gateway: FsGateway, info: OriginInfo): Promise<ApiEndpointSummary[]> {
  const results: ApiEndpointSummary[] = [];

  for (const endpoint of info.apiEndpoints) {
    let responseShape: string | null = null;
    let typeNode: TypeNode | null = null;

    if (endpoint.mimeType.includes("json")) {
      try {
        const bodyText = await gateway.readText(rootPath, `${endpoint.fixtureDir}/response.body`);
        const parsed = JSON.parse(bodyText);
        responseShape = inferJsonShape(parsed);
        typeNode = inferTypeNode(parsed);
      } catch {
        // Fixture body is missing or not valid JSON.
      }
    }

    results.push({
      method: endpoint.method,
      pathname: endpoint.pathname,
      status: endpoint.status,
      mimeType: endpoint.mimeType,
      responseShape,
      typeNode
    });
  }

  return results;
}

function renderContextMarkdown(origins: OriginSummary[], generatedAt: string): string {
  const lines: string[] = [];

  lines.push("# WraithWalker Fixture Context");
  lines.push("");
  lines.push(`Generated: ${generatedAt}`);
  lines.push("");
  lines.push("This file describes the captured network fixtures in this directory.");
  lines.push("It is auto-generated by the WraithWalker CLI or extension.");
  lines.push("");

  for (const origin of origins) {
    lines.push(`## ${origin.origin}`);
    lines.push("");

    if (origin.apiEndpoints.length > 0) {
      lines.push("### API Endpoints");
      lines.push("");
      lines.push("| Method | Path | Status | Content Type |");
      lines.push("|--------|------|--------|--------------|");
      for (const endpoint of origin.apiEndpoints) {
        lines.push(`| ${endpoint.method} | ${endpoint.pathname} | ${endpoint.status} | ${endpoint.mimeType} |`);
      }
      lines.push("");

      const jsonEndpoints = origin.apiEndpoints.filter((endpoint) => endpoint.responseShape);
      if (jsonEndpoints.length > 0) {
        lines.push("### Response Shapes");
        lines.push("");
        for (const endpoint of jsonEndpoints) {
          lines.push(`#### ${endpoint.method} ${endpoint.pathname} (${endpoint.status})`);
          lines.push("");
          lines.push("```typescript");
          lines.push(endpoint.responseShape!);
          lines.push("```");
          lines.push("");
        }
      }
    }

    if (origin.totalStaticAssets > 0) {
      lines.push("### Static Assets");
      lines.push("");
      const parts = Object.entries(origin.staticAssets)
        .sort(([, left], [, right]) => right - left)
        .map(([type, count]) => `${type}: ${count}`);
      lines.push(parts.join(" | "));
      lines.push("");
    }

    if (origin.apiEndpoints.length === 0 && origin.totalStaticAssets === 0) {
      lines.push("No captured fixtures found for this origin.");
      lines.push("");
    }
  }

  if (origins.some((origin) => origin.apiEndpoints.length > 0)) {
    lines.push("## Suggested Agent Tasks");
    lines.push("");
    const firstApiOrigin = origins.find((origin) => origin.apiEndpoints.length > 0);
    if (firstApiOrigin) {
      const endpoint = firstApiOrigin.apiEndpoints[0];
      lines.push(`- Modify the \`${endpoint.method} ${endpoint.pathname}\` fixture to return an error status and test error handling`);
      lines.push(`- Change response data in \`${endpoint.method} ${endpoint.pathname}\` to test edge cases (empty arrays, null fields, large payloads)`);
    }
    lines.push("- Add new fixture files for endpoints that don't exist yet to support offline development");
    lines.push("- Generate TypeScript interfaces from the response shapes above");
    lines.push("");
  }

  return lines.join("\n");
}

export async function generateContext(rootPath: string, gateway: FsGateway, editorId?: string): Promise<string> {
  const configs = await readSiteConfigs(rootPath);
  const origins: OriginSummary[] = [];

  for (const config of configs) {
    const info = await readOriginInfo(rootPath, config);
    const endpoints = await enrichEndpoints(rootPath, gateway, info);
    origins.push(buildOriginSummary(info, endpoints));
  }

  const generatedAt = new Date().toISOString();
  const markdown = renderContextMarkdown(origins, generatedAt);

  const fileNames = EDITOR_CONTEXT_FILES[editorId || ""] || DEFAULT_CONTEXT_FILES;
  for (const fileName of fileNames) {
    await gateway.writeText(rootPath, fileName, markdown);
  }

  const moduleNames: string[] = [];
  for (const origin of origins) {
    const typedEndpoints = origin.apiEndpoints.filter((endpoint) => endpoint.typeNode !== null);
    if (typedEndpoints.length === 0) continue;

    const declarations = new Map<string, { name: string; node: TypeNode }>();
    for (const endpoint of typedEndpoints) {
      const interfaceName = pathToInterfaceName(endpoint.method, endpoint.pathname);
      const existing = declarations.get(interfaceName);
      if (existing && endpoint.typeNode) {
        existing.node = mergeTypeNodes(existing.node, endpoint.typeNode);
      } else if (endpoint.typeNode) {
        declarations.set(interfaceName, { name: interfaceName, node: endpoint.typeNode });
      }
    }

    await gateway.writeText(
      rootPath,
      `.wraithwalker/types/${origin.originKey}.d.ts`,
      renderDtsFile([...declarations.values()])
    );
    moduleNames.push(origin.originKey);
  }

  if (moduleNames.length > 0) {
    await gateway.writeText(rootPath, ".wraithwalker/types/index.d.ts", renderBarrelFile(moduleNames));
  }

  return markdown;
}
